// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBbpkXcUU4W6E2eCx-aIMD11DEqlb37Lo',
    appId: '1:674337940382:web:e7f82028d2e14b6c15ec8f',
    messagingSenderId: '674337940382',
    projectId: 'ecommerceapp-4c0fc',
    authDomain: 'ecommerceapp-4c0fc.firebaseapp.com',
    storageBucket: 'ecommerceapp-4c0fc.firebasestorage.app',
    measurementId: 'G-XMYT709P8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5tqoZQtC_nghismqaFUEjNHCzTaufNuk',
    appId: '1:674337940382:android:e4f75846103d3a9d15ec8f',
    messagingSenderId: '674337940382',
    projectId: 'ecommerceapp-4c0fc',
    storageBucket: 'ecommerceapp-4c0fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj5YXppMpbH8a08ura6ZpqlcM8j2D9apg',
    appId: '1:674337940382:ios:eb81b71ec484cf9215ec8f',
    messagingSenderId: '674337940382',
    projectId: 'ecommerceapp-4c0fc',
    storageBucket: 'ecommerceapp-4c0fc.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj5YXppMpbH8a08ura6ZpqlcM8j2D9apg',
    appId: '1:674337940382:ios:eb81b71ec484cf9215ec8f',
    messagingSenderId: '674337940382',
    projectId: 'ecommerceapp-4c0fc',
    storageBucket: 'ecommerceapp-4c0fc.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAppProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBbpkXcUU4W6E2eCx-aIMD11DEqlb37Lo',
    appId: '1:674337940382:web:6247a7134e0a1dab15ec8f',
    messagingSenderId: '674337940382',
    projectId: 'ecommerceapp-4c0fc',
    authDomain: 'ecommerceapp-4c0fc.firebaseapp.com',
    storageBucket: 'ecommerceapp-4c0fc.firebasestorage.app',
    measurementId: 'G-32KRJ2GQBF',
  );
}
